# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160902_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status_google',
            field=models.CharField(default='IN_PROGRESS', max_length=500),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status_instagram',
            field=models.CharField(default='IN_PROGRESS', max_length=500),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status_yandex',
            field=models.CharField(default='IN_PROGRESS', max_length=500),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='IN_PROGRESS', max_length=500),
        ),
    ]
