# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160906_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='status_google',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='status_instagram',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='status_yandex',
        ),
    ]
