# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160927_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
