# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:17
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tasks_task_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tasks',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
