# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160929_1317'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tasks',
            managers=[
            ],
        ),
    ]
