# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160929_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
